### ISSUE TITLE
build error and run error of bvh build

### ISSUE THREAD

**Issue by neilwhwh** [jan-van-bergen/CPU-Raytracer#3] opened 2022-04-18 09:57 UTC
I try to build this solution to run and see a demo,but there is an error in building: no default constructor available of classs Light.
I just add a simple default construtor, building can pass.
But when start to run and in BVH building, it will hit an assert @ BVHBuilders.h : line 300
Could you please to help to give me some clues of how to fix this issue? 
Brs and  Thanks!

**Comment by jan-van-bergen** [comment] 2022-04-19 12:34
It seems like I was doing some weird non-standard way of initializing arrays, I'm actually not sure why it worked in the first place, but it should be fixed in 9f25311.

The BVH building error I can't seem to reproduce. You could try to circumvent the issue by using the BVH instead of the SBVH. You can do that by changing `MESH_ACCELERATOR` from `MESH_ACCELERATOR_SBVH` to `MESH_ACCELERATOR_BVH` in `Config.h`.

**Comment by neilwhwh** [comment] 2022-04-20 04:50
1. This issue is fixed, thanks a lot~~
2. The SBVH building issue still exist as below image shows. I have tried it on 2 different PCs, both sync the latest codes from github.
![image](https://user-images.githubusercontent.com/63443948/164150228-b7171554-463f-4065-85a8-9f27b4a94e78.png)
3. Then I switch to BVH, the building success, but meet an other error, seems like a draw issue:
![image](https://user-images.githubusercontent.com/63443948/164152699-870eac04-ee01-4a34-b6b0-a9c7e9cf3a66.png)

**Comment by jan-van-bergen** [comment] 2022-04-20 18:53
Ah okay I think I understand what is going on right now, its been a while since I touched this project.
The problem is that you are running in debug mode, in release mode everything should be fine.

The sbvh implementation in this project is slightly buggy, which is why the assert is hit (in release mode those are simply ignored :P). Iirc it had something to do with float precision.
For a better version you should look at my [GPU Raytracer project](https://github.com/jan-van-bergen/GPU-Raytracer).

**Comment by charles-wh** [comment] 2022-04-21 07:38
WOW~ it works in release mode, thanks very much~! 
I've been learned GPU Raytracer for a while, these two project both valuable for me.
After running CPU version, I see every frame in real time rendering have no noise point, while the GPU version has very obvious noise if disable the SVGF. I'm confused about this, it seems like no de-noiser in the CPU version.  
Thanks~

**Comment by jan-van-bergen** [comment] 2022-04-21 18:59
They are different raytracer types. 
The GPU raytracer is a pathtracer but the CPU raytracer is a Whitted style raytracer. This means it doesnt involve any randomness, so there is no noise. But this also means it doesnt support stuff like area lights or indirect illumination.

**Comment by charles-wh** [comment] 2022-04-22 05:07
Got it~! thanks!!

**Closed by charles-wh** 2022-04-22 05:07 UTC
